jobs:
  syntax-check:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build WPF Project
      run: |
        dotnet build YourWPFProject/YourWPFProject.csproj --configuration Release /p:Platform="AnyCPU" /p:WarningLevel=6 /p:DebugType=None /p:DebugSymbols=false /p:Platform="Any CPU" /p:TreatWarningsAsErrors=true /p:DefineConstants=TRACE